### ISSUE TITLE
Error while running the code.

### ISSUE THREAD

**Issue by kpatel-wgsn** [parth1993/pycolor_detection#1]
cv2.error: OpenCV(3.4.3) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by parth1993** [comment]
@kpatel-wgsn  Error has been fixed. Please pull the project and re-run. If still you encounter some issues, feel free to ping.
